MD = "docs/01-nen-tang-llm.md"
MODULE = "01"
PREFIX = "1"

FIGS = [
    ("Sau 5 phép gộp, *hoàn*", "bpe-merges",
     "Ví dụ BPE của mục 1.2: năm phép gộp theo thứ tự tần suất cặp, và kết quả tách của từng từ sau khi gộp."),
    ("**Ví dụ nhỏ.** Giả sử $p(\\text{đăng})", "unigram-viterbi",
     "Unigram LM xem mỗi cách tách là một đường đi trên lưới; Viterbi chọn đường có tổng log-prob cao nhất."),
    ("> **Liên hệ Zendesk — ngân sách token.**", "token-premium",
     "Trái: tỉ lệ token Việt/Anh theo phép đo cộng đồng nêu trong bài (mẫu nhỏ, chỉ nên coi là bậc độ lớn). Phải: số token của một email ~250 từ theo giả định của mục này."),
    ("Nhiều model dùng **weight tying**", "embedding-lmhead",
     "Embedding là tra một hàng của E; LM head chiếu trạng thái ẩn cuối thành logits. Khi tie, cùng một ma trận E được dùng ở cả hai đầu."),
    ("Token 1 chỉ \"thấy\" chính nó", "attention-example",
     "Ví dụ tính tay của mục 3.1: ma trận trọng số sau causal mask, và mỗi đầu ra là tổ hợp lồi của các vector value."),
    ("Jacobian của softmax là", "sqrt-dk",
     "Trái: mô phỏng phân bố của q·k với d_k = 128 trước và sau khi chia √d_k. Phải: hai phân phối softmax so sánh trong bài."),
    ("**MQA / GQA.**", "gqa",
     "MHA, GQA và MQA khác nhau ở số bộ K,V dùng chung (minh họa với 8 đầu query). Llama 3 8B dùng 32 đầu query và 8 bộ K,V."),
    ("Ví dụ: $\\mathbf{x} = (2, -1, 3, 0)$", "rmsnorm",
     "Ví dụ của mục 3.6: cùng vector x sau RMSNorm và LayerNorm (γ = 1, β = 0)."),
    ("Hai nhận xét thực tế. (1) FFN", "param-count",
     "Phân bổ tham số của kiến trúc kiểu Llama-2-7B theo bảng ở mục 3.7, và bộ nhớ trọng số so với GPU 6 GB."),
    ("Mỗi cặp chiều là một \"kim đồng hồ\"", "sinusoidal",
     "Positional encoding sinusoidal với d = 64: các cặp chiều đầu dao động nhanh theo vị trí, các cặp cuối gần như không đổi."),
    ("Điểm attention không đổi khi *dịch*", "rope",
     "Ví dụ số của mục 4.3 (q = (1, 0), k = (0,6; 0,8), θ = 0,5): điểm attention sau RoPE chỉ phụ thuộc khoảng cách m − n."),
    ("| YaRN | Nội suy theo nhóm tần số", "rope-scaling",
     "Tỉ lệ tần số quay mới so với gốc khi mở rộng context 4 lần (d = 128). Đường YaRN là minh họa với tham số giả định α = 1, β = 32, cửa sổ gốc 4K."),
    ("Gradient = \"dự đoán trừ sự thật\"", "ce-gradient",
     "Gradient của cross-entropy theo logit bằng p − y; số liệu theo ví dụ z = (2, 1, 0) của mục 5.1."),
    ("**Ví dụ.** Model gán xác suất $(0.5, 0.25", "perplexity",
     "Ví dụ của mục 5.2: loss từng token, loss trung bình và perplexity."),
    ("- Nếu huấn luyện 7B đó trên 2T token", "chinchilla",
     "Loss dự đoán theo công thức Chinchilla cho model 7B khi tăng số token huấn luyện. Điểm 15T token chỉ để minh họa xu hướng, vẫn dùng N = 7B."),
    ("| 2 | (0,506; 0,307; 0,186) | 1,02 |", "temperature",
     "Bảng temperature của mục 6.2 vẽ thành đồ thị: T đổi độ nhọn của phân phối nhưng không đổi thứ hạng."),
    ("- Nếu phân phối là $(0.96, 0.02", "top-p",
     "Ví dụ top-p của mục 6.3: chọn tập nhỏ nhất có tổng xác suất ≥ p rồi chuẩn hóa lại."),
    ("**Ví dụ số.** $\\beta = 0.1$. Với một cặp", "preference-loss",
     "Reward model Bradley–Terry và DPO dùng chung dạng loss −ln σ(Δ); hai điểm là hai ví dụ số trong mục 7.2 và 7.3."),
    ("> **Liên hệ Zendesk.** Với ~300 macro", "icl-prompt",
     "Cấu trúc prompt gợi ý cho bài toán Zendesk: demonstrations dạy văn phong, tách biệt với tài liệu dùng làm căn cứ."),
    ("Bộ nhớ KV cache tăng tuyến tính", "kv-cache",
     "Hai pha suy luận: prefill xử lý cả prompt và điền KV cache; decode sinh từng token và attend vào cache."),
    ("**Ví dụ.** Mixtral 8x7B", "moe",
     "Mixture of Experts: router chọn top-2 trong 8 chuyên gia cho mỗi token (trọng số g chỉ để minh họa)."),
]
