MD = "docs/04-ingestion-va-chunking.md"
MODULE = "04"
PREFIX = "4"

FIGS = [
    ("Thứ tự ưu tiên thẩm quyền mình khuyên dùng", "authority-tiers",
     "Thang thẩm quyền của các nguồn (authority_tier): nguồn càng nhiều về khối lượng thì càng thấp về thẩm quyền."),
    ("\"Tiếng Việt\" có 10 code point ở NFC", "unicode-forms",
     "Trái: cùng một chữ «ệ» ở dạng NFC và NFD. Phải: NFKC gộp các biến thể trình bày — hữu ích cho tiếng Nhật, nhưng cẩn thận với mã lỗi và ký hiệu."),
    ("Chỉ dòng đầu tiên là *nội dung mới*", "email-anatomy",
     "Giải phẫu comment email ở ví dụ mục 4.1: chỉ một dòng là nội dung mới, phần còn lại phải cắt trước khi embed."),
    ("$|A\\cap B| = 5$, $|A\\cup B| = 9$", "jaccard-shingles",
     "Tập shingle 2 từ của hai câu ở ví dụ mục 5.2 và độ tương đồng Jaccard."),
    ("**Ví dụ số.** Với $J=0.7$: $k=64$", "minhash-variance",
     "Trái: độ lệch chuẩn của ước lượng MinHash giảm theo 1/√k. Phải: với k = 128, phân phối Ĵ (mô phỏng) của các cặp J = 0.5, 0.7, 0.85 tách nhau rõ, nhưng vẫn chồng lấn ở mức sai khác 0.05."),
    ("**Đọc bảng:** để bắt cặp $J\\ge 0.8$", "lsh-s-curve",
     "Xác suất thành ứng viên 1 − (1 − sʳ)ᵇ cho ba cách chia băng của bảng mục 5.4; đường chấm là ngưỡng s* ≈ (1/b)^(1/r)."),
    ("Khung pháp lý và chính sách lưu trữ: Module 11.", "pii-redaction",
     "Che PII bằng placeholder có kiểu và nhất quán trong tài liệu; chuỗi số không qua kiểm tra Luhn được giữ nguyên."),
    ("Chuỗi số ngẫu nhiên chỉ có xác suất 1/10 qua Luhn", "luhn-check",
     "Tính tay kiểm tra Luhn cho số 79927398713: các chữ số ở vị trí chẵn (cam) được nhân đôi và trừ 9 nếu lớn hơn 9."),
    ("với $q_{\\text{csat}}\\in\\{1", "ticket-weight-decay",
     "Trọng số w = q_csat · exp(−Δt/T) với T = 365 ngày và ba ví dụ của mục 7.2."),
    ("không có kích thước tối ưu tuyệt đối", "chunk-size-model",
     "Bốn hiệu ứng của mô hình định lượng mục 8.2 vẽ liên tục theo s; các điểm là những hàng của bảng ví dụ."),
    ("**Ví dụ số (số chunk):**", "fixed-overlap",
     "Fixed-size + overlap trên tài liệu 2.600 token: 8 cửa sổ, phần cam là token bị lưu lặp."),
    ("Quy tắc: không cắt giữa bảng, khối code", "heading-aware",
     "Chunking theo heading: mỗi mục H2 thành một chunk, mang heading path làm ngữ cảnh."),
    ("**Ví dụ số.** 8 câu, cosine giữa các cặp liền kề", "semantic-chunking",
     "Semantic chunking trên ví dụ 8 câu: cắt tại các ranh giới có δ vượt phân vị 80."),
    ("Hình thức hóa: với các child $c$ thuộc parent $P$", "parent-child",
     "Small-to-big: chấm điểm trên child, trả về parent; điểm parent là max điểm child (số minh họa)."),
    ("So với cách thường $\\mathbf{e}_j", "late-chunking",
     "Cắt rồi encode so với late chunking: ở late chunking, vector token đã «thấy» cả tài liệu trước khi bị chia đoạn."),
    ("**Kết quả họ báo cáo**", "contextual-retrieval",
     "Trái: chunk được ghép đoạn ngữ cảnh do LLM viết. Phải: tỷ lệ truy hồi thất bại top-20 theo số liệu Anthropic công bố (9/2024), phần trăm giảm so với baseline."),
    ("**Ý tưởng (Chen et al., 2023, \"Dense X Retrieval\")", "proposition",
     "Proposition indexing trên ví dụ của mục 8.9: đoạn văn thành các mệnh đề tự đủ nghĩa."),
    ("**Diff theo hash chunk.**", "hash-diff",
     "Cập nhật tăng dần theo content_hash: chỉ chunk có hash mới được embed lại."),
    ("Cần: **bảng lineage**", "deletion-lineage",
     "Một yêu cầu xóa lan tới mọi dạng dẫn xuất; bảng lineage là thứ cho biết phải xóa những gì."),
]
