MD = "docs/05-retrieval-sparse-dense-hybrid.md"
MODULE = "05"
PREFIX = "5"

FIGS = [
    ("ANN recall 99% vẫn có thể đi cùng relevance recall 60%", "two-recalls",
     "Hai loại recall đo hai thứ khác nhau: hàm điểm (relevance recall) và thuật toán tìm kiếm xấp xỉ (ANN recall)."),
    ("Vì cả ba nhóm đều xuất hiện hằng ngày", "query-types",
     "Ba kiểu truy vấn trong email Zendesk và loại retrieval «ưa» từng kiểu."),
    ("Với truy vấn có $|q|$ term, chỉ cần duyệt", "inverted-index",
     "Inverted index: truy vấn chỉ chạm tới posting list của các term mà nó chứa."),
    ("Thứ hạng: **d2 > d3 > d1**", "bm25-example",
     "Điểm BM25 của ví dụ mục 2.4, tách theo đóng góp của từng term."),
    ("| 1 (chuẩn hóa hoàn toàn) | 1,375 | 1,000 | 0,647 |", "bm25-k1-b",
     "Trái: hàm saturation với các giá trị k₁ (điểm xanh là bảng k₁ = 1.2). Phải: chuẩn hóa độ dài với các giá trị b (điểm xanh là hàng b = 0.75 của bảng)."),
    ("**Thực hành tốt:** index **hai trường**", "tokenization-vi-ja",
     "Các chiến lược tokenization cho BM25 với tiếng Việt và tiếng Nhật."),
    ("Cây k-d/ball tree hiệu quả ở chiều thấp", "distance-concentration",
     "Lời nguyền số chiều (mô phỏng): tỷ số khoảng cách xa nhất / gần nhất tiến về 1 khi D tăng, nên cây phân hoạch mất tác dụng."),
    ("**Ví dụ số:** $N = 10^6$, $n_{\\text{list}} = 1024$", "ivf",
     "Trái: IVF trên dữ liệu 2D mô phỏng — chỉ quét các cụm được probe. Phải: chi phí truy vấn theo n_list, cực tiểu tại √(n_probe·N)."),
    ("Giá trị lệch nhưng **thứ tự được bảo toàn**", "pq-adc",
     "Product Quantization và ADC; bảng tra T₁, T₂ và hai khoảng cách lấy đúng từ ví dụ số tính tay."),
    ("nên $P(\\ell \\ge L) = M^{-L}$", "hnsw",
     "Trái: sơ đồ HNSW trên dữ liệu mô phỏng — tìm tham lam ở tầng thưa, điểm dừng làm điểm vào tầng dưới. Phải: số điểm kỳ vọng ở mỗi tầng với N = 10⁶, M = 16."),
    ("Kết quả: tỷ vector trên một máy", "diskann",
     "DiskANN: vector nén trong RAM để định hướng, vector đầy đủ và danh sách láng giềng nằm cạnh nhau trên SSD."),
    ("với $\\gamma \\approx 1{,}1\\text{–}1{,}5$", "memory-1m",
     "Bảng ước lượng bộ nhớ mục 3.8 dưới dạng cột chồng."),
    ("BM25 và dense mắc lỗi ở **những chỗ khác nhau**", "hybrid-union",
     "Trái: lợi ích của hợp hai danh sách khi lỗi độc lập. Phải: khi hai biến «trượt» tương quan dương ρ, lợi ích giảm dần (mô hình Bernoulli có tương quan)."),
    ("A và C (có mặt ở cả hai) bỏ xa phần còn lại", "rrf-k",
     "Trái: trọng số 1/(k + rank) theo k. Phải: điểm RRF của ví dụ mục 4.2, tách theo nguồn đóng góp."),
    ("Khác RRF, convex **dùng được độ lớn chênh lệch điểm**", "convex-alpha",
     "Điểm hybrid của từng tài liệu trong ví dụ mục 4.3 khi α thay đổi; ba đường chấm là ba hàng của bảng."),
    ("Với $s = 0{,}01$, ~72% nút không có láng giềng hợp lệ", "filter-selectivity",
     "Trái: post-filter cần k′ ≈ k/s ứng viên. Phải: xác suất một nút HNSW mất hết láng giềng hợp lệ, (1 − s)^M₀."),
    ("Thực tế hay dùng **lai**", "tenant-isolation",
     "Ba mức cô lập multi-tenant; mỗi màu là dữ liệu của một tenant."),
]
