MD = "docs/08-kien-truc-rag-nang-cao.md"
MODULE = "08"
PREFIX = "8"

FIGS = [
    ("Hình thức hóa: tại bước $t$, hệ thống có trạng thái", "control-loop",
     "Từ đường ống cố định sang chính sách điều khiển π chọn hành động theo trạng thái."),
    ("Nếu cho *mọi* ticket đi qua agent (5 lượt)", "routing-cost",
     "Số lượt LLM kỳ vọng của ví dụ mục 1.2: định tuyến (≈ 2,1) so với cho mọi ticket qua agent (5)."),
    ("Ý tưởng sâu hơn nằm ở *cách tạo nhãn*", "adaptive-rag",
     "Adaptive-RAG tạo nhãn bằng cách chạy cả ba chiến lược và chọn chiến lược rẻ nhất vẫn trả lời đúng."),
    ("**Ví dụ số.** Email đang viết: \"Để bật SSO", "flare-tokens",
     "FLARE trên ví dụ mục 2.2: token thấp nhất dưới θ kích hoạt retrieve; token dưới β bị che khỏi truy vấn."),
    ("Ứng viên từ $d_1$ được chọn.", "selfrag-scores",
     "Điểm phê bình Self-RAG của hai tài liệu trong ví dụ, tách theo IsRel/IsSup/IsUse, với w_Sup = 1 và 2."),
    ("**Ví dụ số.** Email: \"API rate limit", "crag-thresholds",
     "Hai ngưỡng của CRAG chia trục điểm thành ba vùng hành động; hai bộ điểm là hai ví dụ trong bài."),
    ("Trực giác: mỗi câu suy luận \"đẩy\" query", "multihop",
     "Trái: vết ReAct/IRCoT của ví dụ mục 4.3. Phải: xác suất có đủ chuỗi tài liệu với một lần và hai bước retrieve (số minh họa của mục 4.1)."),
    ("Khi truy vấn, cách tốt nhất trong bài là **collapsed tree**", "raptor-tree",
     "RAPTOR: cây tóm tắt xây từ dưới lên, và collapsed tree trải phẳng mọi node vào một chỉ mục."),
    ("Chọn $K = 5$ (log-likelihood là số giả định để minh họa)", "gmm-bic",
     "Trái: GMM cho phân cụm mềm (dữ liệu mô phỏng; vòng đen là điểm thuộc hơn một cụm). Phải: BIC của ví dụ mục 5.3."),
    ("Nếu gộp tất cả vào một cộng đồng: $Q", "modularity",
     "Đồ thị 6 node của ví dụ mục 6.3 và modularity của phân hoạch hai cộng đồng."),
    ("HippoRAG 2 (Gutiérrez et al., 2025", "ppr",
     "Personalized PageRank trên một đồ thị đồ chơi với seed «SSO»: các node gần seed theo nhiều đường nhận điểm cao."),
    ("với $\\rho$ là tỷ lệ câu hỏi bị chuyển", "selfroute-cost",
     "Chi phí kỳ vọng của Self-Route theo tỷ lệ chuyển ρ, với giả định c_LC = 20·c_RAG."),
    ("**Ví dụ số.** Một model cỡ 8B kiểu GQA", "cag-kv-memory",
     "Bộ nhớ KV cache cho các kho tri thức theo công thức mục 7.2 (trục log); kho chính sách dùng giả định ~30K token."),
    ("Với CS production, mình khuyên dừng ở mức thứ tư", "agent-spectrum",
     "Dải mức tự chủ của hệ thống RAG; mức được khuyến nghị cho CS là agent có tool nằm trong đồ thị ràng buộc."),
    ("Hình thức hóa: LangGraph là một máy trạng thái", "langgraph-state",
     "LangGraph như một máy trạng thái: node trả về cập nhật, reducer gộp vào state, cạnh điều kiện chọn node tiếp."),
    ("Chi tiết then chốt: **định danh tenant không phải là tham số LLM điền**", "mcp-tenant",
     "org_id đi từ state qua adapter, không đi qua LLM; agent chỉ thấy các tool chỉ đọc trong allowlist."),
    ("Lộ trình mình khuyên: bắt đầu với naive", "architecture-by-route",
     "Kiến trúc đề xuất cho từng loại ticket theo bảng mục 9.2."),
]
