MD = "docs/09-fine-tuning-cho-rag.md"
MODULE = "09"
PREFIX = "9"

FIGS = [
    ("Với Zendesk, điều này có hệ quả rất cụ thể", "where-to-finetune",
     "Bốn chỗ có thể hỏng trong RAG và công cụ tương ứng: luôn thử cách rẻ trước, fine-tune đúng thành phần đang hỏng."),
    ("**Ước lượng sản lượng (giả định để học).**", "weak-pairs-funnel",
     "Ước lượng sản lượng cặp huấn luyện từ ticket lịch sử theo các tỷ lệ giả định của mục 2.1."),
    ("Và quan trọng nhất: **golden set của Module 10", "leak-free-split",
     "Chia dữ liệu không rò rỉ: theo thời gian, theo nhóm tài liệu, và tách hẳn golden set."),
    ("**Vai trò của $\\gamma$ (hay $\\tau$).**", "mnrl-cases",
     "Trái: phân phối softmax và loss của ba trường hợp trong bảng mục 3.2. Phải: loss của trường hợp negative dễ theo hệ số scale γ."),
    ("4. Lấy mẫu kiểm tra tay 100 bộ ba", "positive-aware-mining",
     "Positive-aware mining (số minh họa): loại ứng viên cùng họ tài liệu và ứng viên có điểm vượt 95% điểm positive."),
    ("**VRAM để fine-tune embedding.**", "embedding-vram",
     "Bộ nhớ cho full fine-tune theo quy tắc 16 byte/tham số của mục 3.6."),
    ("Ưu điểm: đầu ra $\\hat p$ có nghĩa xác suất", "reranker-bce",
     "Binary cross-entropy cho reranker với hai ví dụ của mục 4.2."),
    ("**Ví dụ số.** $|x| = 2.400$, $|y| = 200$ token", "sft-mask",
     "Vì sao phải mask phần prompt khi SFT cho RAG."),
    ("Trường `answer_plan` + `claims` của schema Module 07", "raft-mix",
     "Hỗn hợp dữ liệu RAFT điều chỉnh cho Zendesk và mẫu loại A của ví dụ giới hạn API."),
    ("Phiên bản thứ ba thắng.", "abstention-tradeoff",
     "Bốn phiên bản của bảng mục 5.4 trên mặt phẳng AnsRate / AbsRate, kèm chi phí trên 500 câu."),
    ("**Ví dụ số.** $P_\\theta(y_w) = 0{,}6$", "dpo-orpo",
     "Trái: loss DPO theo hiệu phần thưởng ngầm (β = 0.1). Phải: số hạng phạt odds ratio của ORPO; các điểm là ví dụ trong bài."),
    ("**Số tham số một ma trận**", "lora",
     "LoRA: nhánh hạng thấp B·A cộng vào đầu ra của W₀ đóng băng."),
    ("So với tổng tham số: model 1.7B", "lora-params",
     "Tham số LoRA r = 16 cho từng ma trận chiếu của Qwen3-1.7B và Qwen3-4B (bảng mục 7.2)."),
    ("*Ví dụ tính tay:* block có absmax", "nf4-levels",
     "16 mức NF4 (giá trị theo bitsandbytes) so với 16 mức INT4 đều, cùng ví dụ lượng tử hóa của mục 7.3."),
    ("**Bài học quan trọng nhất: thủ phạm OOM", "qlora-vram",
     "Ước lượng VRAM QLoRA theo bảng mục 7.4 (dùng giữa dải cho phần CUDA/tính lại lớp); phần gạch là logits và gradient của chúng."),
    ("Reverse KL khoan dung hơn với việc bỏ một mode", "forward-reverse-kl",
     "Trái: minh họa học trò theo forward KL (phủ) và reverse KL (chọn). Phải: hai giá trị KL của ví dụ mục 8.2."),
    ("4. **Cổng phát hành (regression gate)**", "release-gate",
     "Cổng phát hành adapter: mọi điều kiện phải đạt trước khi vào shadow mode."),
]
