MD = "docs/10-danh-gia-rag.md"
MODULE = "10"
PREFIX = "10"

FIGS = [
    ("AP phạt cả việc thiếu tài liệu ($F$)", "retrieval-metrics",
     "Ví dụ xuyên suốt mục 2: danh sách top-5, tài liệu F bị bỏ sót, và các metric retrieval tính tay."),
    ("Chỉ cần hoán đổi hai tài liệu đầu", "ndcg",
     "Gain có chiết khấu ở từng vị trí cho thứ tự thực tế và thứ tự lý tưởng của ví dụ nDCG."),
    ("> **Khuyến nghị thực tế.** Bắt đầu với 300–500 truy vấn thật", "pooling-labels",
     "Gán nhãn bằng pooling: tài liệu liên quan mà không retriever nào lấy được thì không bao giờ có nhãn."),
    ("> **Cách đọc kết hợp.**", "ragas-diagnosis",
     "Đọc kết hợp context recall, faithfulness và correctness để tìm vị trí lỗi."),
    ("Phương sai xấp xỉ là $\\mathrm{Var}(f)/N", "ppi",
     "Ví dụ PPI của mục 3.5: ước lượng của judge được trừ đi độ lệch đo trên tập có nhãn người."),
    ("Với judge này, dùng nó làm **cổng an toàn", "judge-kappa",
     "Ma trận đồng thuận người–judge của mục 4.3 và các chỉ số rút ra."),
    ("Thay số: $\\pi = (0{,}12 + 0{,}933 - 1)", "rogan-gladen",
     "Hiệu chỉnh Rogan–Gladen: từ tỷ lệ FAIL judge báo suy ra tỷ lệ lỗi thật."),
    ("Mỗi nhóm lại phân tầng theo ngôn ngữ (vi/en/ja)", "golden-composition",
     "Thành phần gợi ý của golden set theo bảng mục 5.1."),
    ("Với $p \\approx 0{,}9$ và $E = 0{,}03$", "wilson-intervals",
     "Trái: khoảng Wilson 95% cho 89% và 91% trên 200 mẫu. Phải: cỡ mẫu cần cho sai số ±E."),
    ("với 1 bậc tự do cho $p \\approx 0{,}046$", "mcnemar",
     "Kiểm định McNemar chỉ dùng các test case mà hai phiên bản bất đồng."),
    ("Nếu có lỗi, dùng cận trên Clopper–Pearson hoặc Wilson", "rule-of-three",
     "Cận trên của tỷ lệ lỗi theo số ticket kiểm tra: khi không thấy lỗi nào (quy tắc số 3) và khi thấy 2 lỗi."),
    ("Ví dụ $N = 5$: nếu cả 5 câu trả lời cùng nghĩa", "semantic-entropy",
     "Entropy ngữ nghĩa của hai ví dụ trong mục 7.3(d): mỗi màu là một cụm cùng nghĩa."),
    ("> **Liên hệ Zendesk.** Mỗi ticket ở giai đoạn 1 lưu lại", "meta-model",
     "Mô hình meta kết hợp các họ tín hiệu confidence, rồi hiệu chuẩn trên một tập riêng."),
    ("3. **Isotonic regression.**", "reliability",
     "Trái: reliability diagram của bảng mục 7.5 (vạch đỏ là độ lệch). Phải: temperature và Platt scaling với các tham số của ví dụ."),
    ("Vậy vùng quyết định là:", "three-action-cost",
     "Trái: chi phí kỳ vọng của ba hành động cho how_to và hai ngưỡng 0,333 / 0,923. Phải: ngưỡng SEND theo intent của bảng mục 7.6."),
    ("Hệ quả quan trọng: ở intent có ít ticket", "risk-coverage",
     "Trái: đường risk–coverage của ví dụ 10 ticket. Phải: quy trình chọn ngưỡng theo ràng buộc rủi ro."),
    ("Khoảng cách chuỗi không phân biệt được", "ned-levels",
     "Các mức NED dùng làm nhãn cho mô hình confidence, kèm ví dụ của mục 8.1."),
    ("Kết luận thực tế: **CSAT là thước đo chậm và nhiễu**", "ab-sample-size",
     "Cỡ mẫu cần để phát hiện CSAT giảm δ (α = 5% hai phía, power 80%); điểm đánh dấu là ví dụ δ = 0,03."),
    ("Nguyên tắc: gate an toàn dùng **ngưỡng tuyệt đối**", "eval-gates",
     "Hai loại gate trong CI theo bảng mục 9.2."),
]
